// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeGenE3uZpROASM2LtiVdp5cuPshxzLTk',
    appId: '1:1082070056103:web:9086ed1511a735cf8e2f82',
    messagingSenderId: '1082070056103',
    projectId: 'e-commerce-a6268',
    authDomain: 'e-commerce-a6268.firebaseapp.com',
    storageBucket: 'e-commerce-a6268.appspot.com',
    measurementId: 'G-WK6TYH3VCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT1G0gp79E6nmAKcEHrew_p3GcSo67S6Q',
    appId: '1:1082070056103:android:253e07456566fa758e2f82',
    messagingSenderId: '1082070056103',
    projectId: 'e-commerce-a6268',
    storageBucket: 'e-commerce-a6268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_CUqtKofza3WlvEx8-7eLJdsfmFIFH1Q',
    appId: '1:1082070056103:ios:10e8c2cc86aea2288e2f82',
    messagingSenderId: '1082070056103',
    projectId: 'e-commerce-a6268',
    storageBucket: 'e-commerce-a6268.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_CUqtKofza3WlvEx8-7eLJdsfmFIFH1Q',
    appId: '1:1082070056103:ios:222643ad1869bd1e8e2f82',
    messagingSenderId: '1082070056103',
    projectId: 'e-commerce-a6268',
    storageBucket: 'e-commerce-a6268.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
